name: Docker Build

on: 
  push:
    branches: [ master ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Dockerhub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build & Push SSR Server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: manedurphy/ssr-service:latest
          
      - name: Build & Push Client
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile.prod
          push: true
          tags: manedurphy/client-service:latest
          build-args:
            - KEY: ${{ secrets.KEY }}
